/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DATE_H_RPCGEN
#define _DATE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct struct_pair {
	int a;
	int b;
};
typedef struct struct_pair struct_pair;

#define DATE_PROG 111222333
#define DATE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define BIN_DATE 1
extern  long * bin_date_1(void *, CLIENT *);
extern  long * bin_date_1_svc(void *, struct svc_req *);
#define STR_DATE 2
extern  char ** str_date_1(long *, CLIENT *);
extern  char ** str_date_1_svc(long *, struct svc_req *);
extern int date_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define BIN_DATE 1
extern  long * bin_date_1();
extern  long * bin_date_1_svc();
#define STR_DATE 2
extern  char ** str_date_1();
extern  char ** str_date_1_svc();
extern int date_prog_1_freeresult ();
#endif /* K&R C */

#define NEW_PROG 123456789
#define NEW_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define DIFF_TIME 1
extern  long * diff_time_1(long *, CLIENT *);
extern  long * diff_time_1_svc(long *, struct svc_req *);
#define MULT 2
extern  float * mult_1(struct struct_pair *, CLIENT *);
extern  float * mult_1_svc(struct struct_pair *, struct svc_req *);
extern int new_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define DIFF_TIME 1
extern  long * diff_time_1();
extern  long * diff_time_1_svc();
#define MULT 2
extern  float * mult_1();
extern  float * mult_1_svc();
extern int new_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_struct_pair (XDR *, struct_pair*);

#else /* K&R C */
extern bool_t xdr_struct_pair ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DATE_H_RPCGEN */
